import type { Channel, Tag } from '@/types';

export const CHANNELS: Channel[] = [
  {
    slug: 'artikel',
    name: 'Artikel Pendidikan',
    description: 'Opini, penelitian, best practice, dan wawancara seputar dunia pendidikan Indonesia',
    icon: 'book-open',
    color: 'text-emerald-600 dark:text-emerald-400',
    bgColor: 'bg-emerald-50 dark:bg-emerald-900/30',
    contentTypes: ['artikel'],
    href: '/artikel',
  },
  {
    slug: 'perencanaan-pembelajaran',
    name: 'Perencanaan Pembelajaran & Capaian',
    description: 'RPP, ATP, Modul, CP/TP/ATP mapping, contoh asesmen Kurikulum Merdeka',
    icon: 'clipboard-list',
    color: 'text-teal-600 dark:text-teal-400',
    bgColor: 'bg-teal-50 dark:bg-teal-900/30',
    contentTypes: ['rpp', 'atp', 'modul', 'cp-tp-atp', 'asesmen'],
    href: '/perencanaan-pembelajaran',
  },
  {
    slug: 'soal-latihan',
    name: 'Soal & Latihan',
    description: 'Bank soal, LKS, simulasi UNBK/ANBK, kisi-kisi untuk berbagai jenjang',
    icon: 'pen-tool',
    color: 'text-green-600 dark:text-green-400',
    bgColor: 'bg-green-50 dark:bg-green-900/30',
    contentTypes: ['soal', 'lks', 'simulasi', 'kisi-kisi'],
    href: '/soal-latihan',
  },
  {
    slug: 'info-guru',
    name: 'Informasi Guru',
    description: 'PKG, tunjangan, kenaikan pangkat, mutasi, info PNS/PPPK guru',
    icon: 'badge-check',
    color: 'text-emerald-600 dark:text-emerald-400',
    bgColor: 'bg-emerald-50 dark:bg-emerald-900/30',
    contentTypes: ['info-pkg', 'tunjangan', 'pangkat', 'mutasi'],
    href: '/info-guru',
  },
  {
    slug: 'beasiswa-kuliah',
    name: 'Beasiswa & Kuliah',
    description: 'Beasiswa dalam/luar negeri, SNBP/SNBT, info PTN/PTS, jurusan kuliah',
    icon: 'graduation-cap',
    color: 'text-green-600 dark:text-green-400',
    bgColor: 'bg-green-50 dark:bg-green-900/30',
    contentTypes: ['beasiswa-dalam', 'beasiswa-luar', 'snbt-snbp', 'info-ptn'],
    href: '/beasiswa-kuliah',
  },
  {
    slug: 'edtech-inovasi',
    name: 'EdTech & Inovasi',
    description: 'Review LMS, AI tools, media pembelajaran digital, sertifikasi teknologi',
    icon: 'cpu',
    color: 'text-teal-600 dark:text-teal-400',
    bgColor: 'bg-teal-50 dark:bg-teal-900/30',
    contentTypes: ['edtech-review', 'ai-tools', 'media-pembelajaran', 'sertifikasi'],
    href: '/edtech-inovasi',
  },
  {
    slug: 'kebijakan',
    name: 'Kebijakan Pendidikan',
    description: 'Kemendikdasmen, Kurikulum Merdeka, regulasi dan kebijakan pendidikan terbaru',
    icon: 'landmark',
    color: 'text-emerald-600 dark:text-emerald-400',
    bgColor: 'bg-emerald-50 dark:bg-emerald-900/30',
    contentTypes: ['kebijakan-kemdikbud', 'kurikulum-merdeka', 'regulasi'],
    href: '/kebijakan',
  },
  {
    slug: 'tips-mengajar',
    name: 'Tips Mengajar',
    description: 'Classroom management, pembelajaran diferensiasi, konseling, literasi, pedagogi',
    icon: 'sparkles',
    color: 'text-green-600 dark:text-green-400',
    bgColor: 'bg-green-50 dark:bg-green-900/30',
    contentTypes: ['tips-mengajar', 'classroom-management', 'diferensiasi', 'konseling', 'literasi'],
    href: '/tips-mengajar',
  },
];

export const FEATURED_TAGS: Tag[] = [
  { id: '1', name: 'Kurikulum Merdeka', slug: 'kurikulum-merdeka', count: 24 },
  { id: '2', name: 'PPPK Guru', slug: 'pppk-guru', count: 18 },
  { id: '3', name: 'SNBP 2026', slug: 'snbp-2026', count: 15 },
  { id: '4', name: 'ANBK', slug: 'anbk', count: 12 },
  { id: '5', name: 'RPP Merdeka', slug: 'rpp-merdeka', count: 20 },
  { id: '6', name: 'Sertifikasi', slug: 'sertifikasi', count: 9 },
  { id: '7', name: 'Beasiswa LPDP', slug: 'beasiswa-lpdp', count: 11 },
  { id: '8', name: 'AI Pendidikan', slug: 'ai-pendidikan', count: 7 },
  { id: '9', name: 'P5', slug: 'p5', count: 14 },
  { id: '10', name: 'Asesmen', slug: 'asesmen', count: 16 },
];

export const SITE_CONFIG = {
  name: 'ideguru',
  tagline: 'Platform Pendidikan Indonesia',
  description: 'Platform informasi, sumber belajar, dan perangkat pembelajaran untuk guru dan tenaga kependidikan di Indonesia.',
  url: 'https://ideguru.id',
  locale: 'id-ID',
  logo: '/logo.svg',
};