import type { ContentItem, Author } from '@/types';

export const AUTHORS: Author[] = [
  { id: 'a1', name: 'Ahmad Fauzi', role: 'Guru SMPN 1 Bandung' },
  { id: 'a2', name: 'Siti Nurhaliza', role: 'Dosen UNJ' },
  { id: 'a3', name: 'Bambang Supriyanto', role: 'Pengawas Sekolah DKI Jakarta' },
  { id: 'a4', name: 'Dewi Lestari', role: 'Guru SDN Menteng 01' },
  { id: 'a5', name: 'Rudi Hermawan', role: 'Konsultan Pendidikan' },
  { id: 'a6', name: 'Fitri Handayani', role: 'Kepala Sekolah SMA Labschool' },
  { id: 'a7', name: 'Hendra Kusuma', role: 'Instruktur Kurikulum Merdeka' },
  { id: 'a8', name: 'Rina Marlina', role: 'Dosen Universitas Pendidikan Indonesia' },
  { id: 'a9', name: 'Agus Wijaya', role: 'Tim Pengembang EdTech' },
  { id: 'a10', name: 'Maya Indah', role: 'Konselor Sekolah' },
];

export const MOCK_TAGS = [
  { id: 't1', name: 'Kurikulum Merdeka', slug: 'kurikulum-merdeka', count: 24 },
  { id: 't2', name: 'RPP', slug: 'rpp', count: 18 },
  { id: 't3', name: 'ATP', slug: 'atp', count: 12 },
  { id: 't4', name: 'ANBK', slug: 'anbk', count: 15 },
  { id: 't5', name: 'PPPK Guru', slug: 'pppk-guru', count: 20 },
  { id: 't6', name: 'SNBP 2026', slug: 'snbp-2026', count: 9 },
  { id: 't7', name: 'Beasiswa LPDP', slug: 'beasiswa-lpdp', count: 11 },
  { id: 't8', name: 'AI Pendidikan', slug: 'ai-pendidikan', count: 7 },
  { id: 't9', name: 'P5', slug: 'p5', count: 14 },
  { id: 't10', name: 'Asesmen', slug: 'asesmen', count: 16 },
  { id: 't11', name: 'Canva', slug: 'canva', count: 6 },
  { id: 't12', name: 'Merdeka Belajar', slug: 'merdeka-belajar', count: 22 },
  { id: 't13', name: 'GTK', slug: 'gtk', count: 8 },
  { id: 't14', name: 'Sertifikasi Guru', slug: 'sertifikasi-guru', count: 13 },
  { id: 't15', name: 'PMM', slug: 'pmm', count: 10 },
];

export const MOCK_CONTENT: ContentItem[] = [
  // === ARTIKEL ===
  {
    id: 'art-1',
    slug: 'implementasi-kurikulum-merdeka-tantangan-dan-solusi',
    title: 'Implementasi Kurikulum Merdeka: Tantangan dan Solusi di Lapangan',
    excerpt: 'Bagaimana guru menghadapi tantangan implementasi Kurikulum Merdeka? Simak pengalaman dan solusi dari berbagai sekolah di Indonesia.',
    content: '<p>Kurikulum Merdeka telah resmi diterapkan di ribuan sekolah di Indonesia. Namun, perjalanan implementasinya tidak selalu mulus. Banyak guru menghadapi tantangan dalam memahami konsep pembelajaran diferensiasi, penyusunan ATP, dan pelaksanaan P5.</p><h2>Tantangan Utama</h2><p>Berdasarkan survei yang dilakukan oleh Kemendikdasmen, tiga tantangan utama yang dihadapi guru adalah: pemahaman konsep Kurikulum Merdeka yang masih beragam, keterbatasan sumber belajar pendukung, dan beban administratif yang masih terasa berat.</p><h2>Solusi dari Lapangan</h2><p>Beberapa sekolah telah menemukan cara efektif untuk mengatasi tantangan ini. Misalnya dengan membentuk komunitas belajar antar guru, memanfaatkan Platform Merdeka Mengajar (PMM), dan melibatkan orang tua dalam proses pembelajaran.</p>',
    channel: 'artikel',
    contentType: 'artikel',
    tags: [MOCK_TAGS[0], MOCK_TAGS[11]],
    author: AUTHORS[0],
    publishedAt: '2026-06-18T08:00:00Z',
    readTime: 8,
    viewCount: 3421,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'art-2',
    slug: 'peran-teknologi-ai-dalam-pembelajaran-masa-depan',
    title: 'Peran Teknologi AI dalam Pembelajaran Masa Depan',
    excerpt: 'Artificial Intelligence mengubah cara kita belajar dan mengajar. Bagaimana guru dapat memanfaatkan AI untuk meningkatkan kualitas pembelajaran?',
    content: '<p>Kecerdasan buatan (AI) telah menjadi bagian tak terpisahkan dari dunia pendidikan global. Di Indonesia, adopsi AI dalam pembelajaran masih dalam tahap awal, namun potensinya sangat besar.</p>',
    channel: 'artikel',
    contentType: 'artikel',
    tags: [MOCK_TAGS[7], MOCK_TAGS[0]],
    author: AUTHORS[4],
    publishedAt: '2026-06-17T10:30:00Z',
    readTime: 10,
    viewCount: 2890,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'art-3',
    slug: 'meningkatkan-literasi-membaca-siswa-sekolah-dasar',
    title: 'Meningkatkan Literasi Membaca Siswa Sekolah Dasar',
    excerpt: 'Program literasi yang efektif untuk meningkatkan minat baca siswa SD. Tips dan strategi dari guru berpengalaman.',
    content: '<p>Literasi membaca merupakan fondasi penting dalam pendidikan. Tanpa kemampuan membaca yang baik, siswa akan kesulitan memahami materi pelajaran lainnya.</p>',
    channel: 'artikel',
    contentType: 'artikel',
    tags: [MOCK_TAGS[9], MOCK_TAGS[0]],
    author: AUTHORS[3],
    publishedAt: '2026-06-16T07:00:00Z',
    readTime: 6,
    viewCount: 1543,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: 'art-4',
    slug: 'wawancara-guru-penggerak-angkatan-4',
    title: 'Wawancara Eksklusif: Kisah Guru Penggerak Angkatan 4',
    excerpt: 'Perjalanan menjadi Guru Penggerak, dampaknya pada pembelajaran, dan pesan untuk calon Guru Penggerak.',
    content: '<p>Program Guru Penggerak telah melahirkan ribuan agen perubahan di dunia pendidikan Indonesia. Kami mewawancarai salah satu Guru Penggerak Angkatan 4 untuk berbagi pengalaman.</p>',
    channel: 'artikel',
    contentType: 'artikel',
    tags: [MOCK_TAGS[5], MOCK_TAGS[13]],
    author: AUTHORS[7],
    publishedAt: '2026-06-15T14:00:00Z',
    readTime: 12,
    viewCount: 2100,
    isFeatured: false,
    isTrending: false,
  },

  // === PERENCANAAN PEMBELAJARAN & CAPAIAN ===
  {
    id: 'rpp-1',
    slug: 'rpp-ips-kelas-7-kurikulum-merdeka',
    title: 'RPP IPS Kelas 7 Semester 1 Kurikulum Merdeka (Lengkap)',
    excerpt: 'Rencana Pelaksanaan Pembelajaran IPS untuk Kelas 7 SMP fase D Kurikulum Merdeka. Lengkap dengan ATP, tujuan pembelajaran, dan asesmen.',
    content: '<p>RPP IPS Kelas 7 Semester 1 ini disusun berdasarkan Capaian Pembelajaran (CP) dan Tujuan Pembelajaran (TP) Kurikulum Merdeka fase D.</p>',
    channel: 'perencanaan-pembelajaran',
    contentType: 'rpp',
    tags: [MOCK_TAGS[1], MOCK_TAGS[0], MOCK_TAGS[9]],
    author: AUTHORS[1],
    publishedAt: '2026-06-18T09:00:00Z',
    readTime: 5,
    viewCount: 5632,
    downloadCount: 1234,
    downloadUrl: '/unduhan/rpp-ips-kelas-7.docx',
    fileSize: '1.2 MB',
    fileType: 'DOCX',
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'rpp-2',
    slug: 'atp-matematika-fase-a-kelas-1',
    title: 'ATP Matematika Fase A Kelas 1 SD Kurikulum Merdeka',
    excerpt: 'Alur Tujuan Pembelajaran Matematika Fase A untuk Kelas 1 SD. Dilengkapi CP, TP, dan indikator pencapaian.',
    content: '<p>ATP Matematika Fase A ini dirancang untuk membantu guru dalam merencanakan pembelajaran matematika di kelas 1 SD.</p>',
    channel: 'perencanaan-pembelajaran',
    contentType: 'atp',
    tags: [MOCK_TAGS[2], MOCK_TAGS[0], MOCK_TAGS[11]],
    author: AUTHORS[3],
    publishedAt: '2026-06-17T11:00:00Z',
    readTime: 4,
    viewCount: 4120,
    downloadCount: 987,
    downloadUrl: '/unduhan/atp-matematika-fase-a.pdf',
    fileSize: '890 KB',
    fileType: 'PDF',
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'rpp-3',
    slug: 'cp-tp-atp-bahasa-indonesia-fase-c',
    title: 'Pemetaan CP TP ATP Bahasa Indonesia Fase C Kelas 5-6',
    excerpt: 'Mapping lengkap Capaian Pembelajaran, Tujuan Pembelajaran, dan Alur Tujuan Pembelajaran Bahasa Indonesia Fase C.',
    content: '<p>Dokumen pemetaan ini menyajikan hubungan antara CP, TP, dan ATP Bahasa Indonesia untuk Fase C (Kelas 5-6 SD).</p>',
    channel: 'perencanaan-pembelajaran',
    contentType: 'cp-tp-atp',
    tags: [MOCK_TAGS[0], MOCK_TAGS[2], MOCK_TAGS[11]],
    author: AUTHORS[6],
    publishedAt: '2026-06-16T13:00:00Z',
    readTime: 6,
    viewCount: 3245,
    downloadCount: 765,
    downloadUrl: '/unduhan/pemetaan-cp-tp-atp-bahasa-indonesia-fase-c.pdf',
    fileSize: '1.5 MB',
    fileType: 'PDF',
    isFeatured: false,
    isTrending: false,
  },
  {
    id: 'rpp-4',
    slug: 'contoh-asesmen-ipa-kelas-8',
    title: 'Contoh Asesmen IPA Kelas 8 Semester 2 Kurikulum Merdeka',
    excerpt: 'Kumpulan soal asesmen formatif dan sumatif IPA Kelas 8 beserta rubrik penilaian dan kisi-kisi.',
    content: '<p>Asesmen merupakan bagian integral dari proses pembelajaran. Dokumen ini berisi contoh asesmen formatif dan sumatif untuk IPA Kelas 8.</p>',
    channel: 'perencanaan-pembelajaran',
    contentType: 'asesmen',
    tags: [MOCK_TAGS[9], MOCK_TAGS[0]],
    author: AUTHORS[2],
    publishedAt: '2026-06-15T10:00:00Z',
    readTime: 5,
    viewCount: 2789,
    downloadCount: 543,
    downloadUrl: '/unduhan/contoh-asesmen-ipa-8.pdf',
    fileSize: '2.1 MB',
    fileType: 'PDF',
    isFeatured: false,
    isTrending: false,
  },
  {
    id: 'rpp-5',
    slug: 'modul-ajar-p5-kearifan-lokal',
    title: 'Modul Ajar P5 Tema Kearifan Lokal Fase D',
    excerpt: 'Modul Projek Penguatan Profil Pelajar Pancasila tema Kearifan Lokal untuk SMP/MTs fase D.',
    content: '<p>Modul P5 ini dirancang untuk membantu guru dalam melaksanakan projek penguatan profil pelajar Pancasila dengan tema kearifan lokal.</p>',
    channel: 'perencanaan-pembelajaran',
    contentType: 'modul',
    tags: [MOCK_TAGS[8], MOCK_TAGS[0], MOCK_TAGS[11]],
    author: AUTHORS[6],
    publishedAt: '2026-06-14T09:00:00Z',
    readTime: 8,
    viewCount: 4567,
    downloadCount: 1102,
    downloadUrl: '/unduhan/modul-p5-kearifan-lokal.pdf',
    fileSize: '3.4 MB',
    fileType: 'PDF',
    isFeatured: true,
    isTrending: false,
  },

  // === SOAL & LATIHAN ===
  {
    id: 'soal-1',
    slug: 'bank-soal-matematika-kelas-9-semester-1',
    title: 'Bank Soal Matematika Kelas 9 Semester 1 (100+ Soal)',
    excerpt: 'Kumpulan soal matematika kelas 9 semester 1 lengkap dengan kunci jawaban dan pembahasan. Cocok untuk persiapan ujian sekolah.',
    content: '<p>Bank soal matematika ini mencakup materi semester 1 kelas 9: bilangan berpangkat, bentuk akar, persamaan kuadrat, dan fungsi kuadrat.</p>',
    channel: 'soal-latihan',
    contentType: 'soal',
    tags: [MOCK_TAGS[5], MOCK_TAGS[0]],
    author: AUTHORS[0],
    publishedAt: '2026-06-18T07:00:00Z',
    readTime: 3,
    viewCount: 6789,
    downloadCount: 2345,
    downloadUrl: '/unduhan/bank-soal-matematika-9.pdf',
    fileSize: '2.5 MB',
    fileType: 'PDF',
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'soal-2',
    slug: 'simulasi-anbk-smp-2026',
    title: 'Simulasi ANBK SMP 2026 Lengkap dengan Pembahasan',
    excerpt: 'Latihan soal ANBK SMP 2026 untuk literasi membaca dan numerasi. Dilengkapi simulasi interaktif dan pembahasan video.',
    content: '<p>ANBK (Asesmen Nasional Berbasis Komputer) akan digelar dalam waktu dekat. Persiapkan diri dengan simulasi lengkap ini.</p>',
    channel: 'soal-latihan',
    contentType: 'simulasi',
    tags: [MOCK_TAGS[3], MOCK_TAGS[0]],
    author: AUTHORS[2],
    publishedAt: '2026-06-17T08:00:00Z',
    readTime: 4,
    viewCount: 5432,
    downloadCount: 1890,
    downloadUrl: '/unduhan/simulasi-anbk-smp-2026.pdf',
    fileSize: '3.2 MB',
    fileType: 'PDF',
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'soal-3',
    slug: 'lks-bahasa-inggris-kelas-4-semester-2',
    title: 'LKS Bahasa Inggris Kelas 4 SD Semester 2',
    excerpt: 'Lembar Kerja Siswa Bahasa Inggris untuk Kelas 4 SD. Materi vocabulary, grammar dasar, dan reading comprehension.',
    content: '<p>LKS Bahasa Inggris ini dirancang untuk membantu siswa kelas 4 SD belajar bahasa Inggris dengan cara yang menyenangkan.</p>',
    channel: 'soal-latihan',
    contentType: 'lks',
    tags: [MOCK_TAGS[0], MOCK_TAGS[5]],
    author: AUTHORS[3],
    publishedAt: '2026-06-16T10:00:00Z',
    readTime: 3,
    viewCount: 3210,
    downloadCount: 987,
    downloadUrl: '/unduhan/lks-inggris-4-2.pdf',
    fileSize: '1.8 MB',
    fileType: 'PDF',
    isFeatured: false,
    isTrending: false,
  },
  {
    id: 'soal-4',
    slug: 'kisi-kisi-pas-pkn-kelas-11',
    title: 'Kisi-kisi PAS PKn Kelas 11 Semester 1 Kurikulum Merdeka',
    excerpt: 'Kisi-kisi soal Penilaian Akhir Semester PKn Kelas 11 beserta contoh soal dan bobot penilaian.',
    content: '<p>Kisi-kisi PAS PKn kelas 11 semester 1 ini disusun berdasarkan CP dan TP Kurikulum Merdeka fase F.</p>',
    channel: 'soal-latihan',
    contentType: 'kisi-kisi',
    tags: [MOCK_TAGS[0], MOCK_TAGS[9]],
    author: AUTHORS[4],
    publishedAt: '2026-06-15T09:00:00Z',
    readTime: 4,
    viewCount: 2567,
    downloadCount: 654,
    downloadUrl: '/unduhan/kisi-kisi-pas-pkn-11.pdf',
    fileSize: '1.1 MB',
    fileType: 'PDF',
    isFeatured: false,
    isTrending: false,
  },

  // === INFO GURU ===
  {
    id: 'info-1',
    slug: 'panduan-sertifikasi-guru-2026',
    title: 'Panduan Lengkap Sertifikasi Guru 2026: Syarat, Tahapan, dan Jadwal',
    excerpt: 'Informasi lengkap tentang sertifikasi guru tahun 2026, mulai dari persyaratan, tahapan seleksi, hingga jadwal pelaksanaan.',
    content: '<p>Sertifikasi guru merupakan program untuk meningkatkan kompetensi dan kesejahteraan guru. Tahun 2026, program ini kembali dibuka dengan beberapa pembaruan.</p>',
    channel: 'info-guru',
    contentType: 'sertifikasi',
    tags: [MOCK_TAGS[13], MOCK_TAGS[12]],
    author: AUTHORS[0],
    publishedAt: '2026-06-18T06:00:00Z',
    readTime: 7,
    viewCount: 8921,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'info-2',
    slug: 'tunjangan-guru-2026-pencairan-dan-besaran',
    title: 'Tunjangan Guru 2026: Jadwal Pencairan, Besaran, dan Syarat',
    excerpt: 'Update terbaru tunjangan profesi guru, tunjangan khusus, dan tunjangan daerah terpencil tahun 2026.',
    content: '<p>Pemerintah telah mengalokasikan anggaran tunjangan guru dalam APBN 2026. Berikut rincian lengkap jadwal pencairan dan besaran tunjangan.</p>',
    channel: 'info-guru',
    contentType: 'tunjangan',
    tags: [MOCK_TAGS[4], MOCK_TAGS[5]],
    author: AUTHORS[5],
    publishedAt: '2026-06-17T07:00:00Z',
    readTime: 6,
    viewCount: 7654,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'info-3',
    slug: 'kenaikan-pangkat-guru-pns-terbaru',
    title: 'Kenaikan Pangkat Guru PNS: Syarat, Berkas, dan Prosedur 2026',
    excerpt: 'Panduan lengkap kenaikan pangkat bagi guru PNS. Persyaratan, dokumen yang diperlukan, dan alur pengajuan.',
    content: '<p>Kenaikan pangkat merupakan salah satu hak guru PNS yang diatur dalam peraturan perundang-undangan. Berikut panduan lengkapnya.</p>',
    channel: 'info-guru',
    contentType: 'pangkat',
    tags: [MOCK_TAGS[4], MOCK_TAGS[5]],
    author: AUTHORS[2],
    publishedAt: '2026-06-16T08:00:00Z',
    readTime: 8,
    viewCount: 5432,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: 'info-4',
    slug: 'info-mutasi-guru-2026',
    title: 'Info Mutasi Guru 2026: Syarat, Prosedur, dan Formasi',
    excerpt: 'Informasi terbaru tentang mutasi guru antar daerah, antar provinsi, dan repatriasi. Dilengkapi dengan formasi yang tersedia.',
    content: '<p>Mutasi guru merupakan proses perpindahan tugas guru dari satu satuan pendidikan ke satuan pendidikan lain. Berikut informasi lengkapnya.</p>',
    channel: 'info-guru',
    contentType: 'mutasi',
    tags: [MOCK_TAGS[4]],
    author: AUTHORS[5],
    publishedAt: '2026-06-15T11:00:00Z',
    readTime: 5,
    viewCount: 3987,
    isFeatured: false,
    isTrending: false,
  },

  // === BEASISWA & KULIAH ===
  {
    id: 'bea-1',
    slug: 'beasiswa-lpdp-2026-pendaftaran-dan-persyaratan',
    title: 'Beasiswa LPDP 2026: Pendaftaran Dibuka! Ini Syarat Lengkapnya',
    excerpt: 'Pendaftaran beasiswa LPDP 2026 telah dibuka. Simak persyaratan, jadwal seleksi, dan tips lolos seleksi beasiswa.',
    content: '<p>Lembaga Pengelola Dana Pendidikan (LPDP) kembali membuka pendaftaran beasiswa untuk tahun 2026. Beasiswa ini mencakup biaya pendidikan penuh untuk studi S2 dan S3 di dalam dan luar negeri.</p>',
    channel: 'beasiswa-kuliah',
    contentType: 'beasiswa-dalam',
    tags: [MOCK_TAGS[6], MOCK_TAGS[5]],
    author: AUTHORS[4],
    publishedAt: '2026-06-18T07:30:00Z',
    readTime: 8,
    viewCount: 12345,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'bea-2',
    slug: 'snbp-2026-jadwal-dan-tips-lolos',
    title: 'SNBP 2026: Jadwal Lengkap, Syarat, dan Tips Lolos Seleksi',
    excerpt: 'Seleksi Nasional Berdasarkan Prestasi (SNBP) 2026 akan segera dibuka. Catat jadwal dan persiapkan diri dengan tips berikut.',
    content: '<p>SNBP merupakan jalur seleksi masuk PTN berdasarkan nilai rapor dan prestasi siswa. Tahun 2026, terdapat beberapa perubahan dalam mekanisme seleksi.</p>',
    channel: 'beasiswa-kuliah',
    contentType: 'snbt-snbp',
    tags: [MOCK_TAGS[5], MOCK_TAGS[3]],
    author: AUTHORS[7],
    publishedAt: '2026-06-17T09:00:00Z',
    readTime: 6,
    viewCount: 9876,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'bea-3',
    slug: 'beasiswa-fulbright-2027-persiapan',
    title: 'Persiapan Beasiswa Fulbright 2027: Panduan dari Alumni',
    excerpt: 'Tips dan strategi lolos beasiswa Fulbright dari para alumni Indonesia. Persiapan dokumen, esai, dan wawancara.',
    content: '<p>Beasiswa Fulbright merupakan salah satu beasiswa paling prestisius untuk studi di Amerika Serikat. Berikut panduan lengkap dari para alumni.</p>',
    channel: 'beasiswa-kuliah',
    contentType: 'beasiswa-luar',
    tags: [MOCK_TAGS[6]],
    author: AUTHORS[1],
    publishedAt: '2026-06-16T10:00:00Z',
    readTime: 10,
    viewCount: 4567,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: 'bea-4',
    slug: 'info-ptn-2026-jurusan-dan-daya-tampung',
    title: 'Info PTN 2026: Daftar Jurusan dan Daya Tampung SNBT',
    excerpt: 'Daftar lengkap jurusan dan daya tampung SNBT 2026 di seluruh PTN Indonesia. Lengkap dengan passing grade tahun sebelumnya.',
    content: '<p>Memilih jurusan dan PTN yang tepat adalah langkah penting dalam meraih pendidikan tinggi. Berikut data lengkap daya tampung dan jurusan di PTN 2026.</p>',
    channel: 'beasiswa-kuliah',
    contentType: 'info-ptn',
    tags: [MOCK_TAGS[5]],
    author: AUTHORS[4],
    publishedAt: '2026-06-15T08:00:00Z',
    readTime: 5,
    viewCount: 6789,
    isFeatured: false,
    isTrending: false,
  },

  // === EDTECH & INOVASI ===
  {
    id: 'edtech-1',
    slug: 'review-lms-google-classroom-vs-moodle-vs-canvas',
    title: 'Review LMS: Google Classroom vs Moodle vs Canvas untuk Sekolah Indonesia',
    excerpt: 'Perbandingan fitur, kemudahan penggunaan, dan biaya dari tiga LMS terpopuler. Mana yang cocok untuk sekolah Anda?',
    content: '<p>Learning Management System (LMS) menjadi semakin penting dalam dunia pendidikan. Berikut perbandingan tiga LMS terpopuler di Indonesia.</p>',
    channel: 'edtech-inovasi',
    contentType: 'edtech-review',
    tags: [MOCK_TAGS[7], MOCK_TAGS[10]],
    author: AUTHORS[8],
    publishedAt: '2026-06-18T10:00:00Z',
    readTime: 9,
    viewCount: 3210,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: 'edtech-2',
    slug: 'ai-tools-untuk-guru-membuat-rpp-dan-materi-ajar',
    title: '5 AI Tools yang Wajib Dikuasai Guru untuk Membuat RPP dan Materi Ajar',
    excerpt: 'Manfaatkan kecerdasan buatan untuk mempercepat pembuatan RPP, materi ajar, dan soal evaluasi. Hemat waktu dan tingkatkan kualitas.',
    content: '<p>AI tools dapat membantu guru menghemat waktu dalam persiapan mengajar. Berikut 5 tools yang wajib Anda coba.</p>',
    channel: 'edtech-inovasi',
    contentType: 'ai-tools',
    tags: [MOCK_TAGS[7], MOCK_TAGS[0]],
    author: AUTHORS[8],
    publishedAt: '2026-06-17T14:00:00Z',
    readTime: 7,
    viewCount: 5432,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'edtech-3',
    slug: 'media-pembelajaran-interaktif-canva-berbasis-game',
    title: 'Cara Membuat Media Pembelajaran Interaktif dengan Canva (Berbasis Game)',
    excerpt: 'Tutorial lengkap membuat media pembelajaran interaktif berbasis game menggunakan Canva. Cocok untuk semua jenjang.',
    content: '<p>Canva bukan hanya untuk desain grafis. Platform ini juga dapat digunakan untuk membuat media pembelajaran interaktif yang menyenangkan.</p>',
    channel: 'edtech-inovasi',
    contentType: 'media-pembelajaran',
    tags: [MOCK_TAGS[10], MOCK_TAGS[0]],
    author: AUTHORS[3],
    publishedAt: '2026-06-16T09:00:00Z',
    readTime: 6,
    viewCount: 4321,
    downloadCount: 543,
    downloadUrl: '/unduhan/tutorial-canva-game.pdf',
    fileSize: '4.2 MB',
    fileType: 'PDF',
    isFeatured: false,
    isTrending: false,
  },

  // === KEBIJAKAN ===
  {
    id: 'keb-1',
    slug: 'kemendikdasmen-luncurkan-kebijakan-baru-tahun-ajaran-2026-2027',
    title: 'Kemendikdasmen Luncurkan Kebijakan Baru Tahun Ajaran 2026/2027',
    excerpt: 'Menteri Pendidikan Dasar dan Menengah mengumumkan sejumlah kebijakan baru untuk tahun ajaran 2026/2027. Simak detailnya.',
    content: '<p>Kementerian Pendidikan Dasar dan Menengah (Kemendikdasmen) meluncurkan serangkaian kebijakan baru yang akan berlaku mulai tahun ajaran 2026/2027.</p>',
    channel: 'kebijakan',
    contentType: 'kebijakan-kemdikbud',
    tags: [MOCK_TAGS[11], MOCK_TAGS[0]],
    author: AUTHORS[5],
    publishedAt: '2026-06-18T08:30:00Z',
    readTime: 7,
    viewCount: 6543,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'keb-2',
    slug: 'implementasi-kurikulum-merdeka-wajib-2027',
    title: 'Implementasi Kurikulum Merdeka Wajib 2027: Persiapan yang Harus Dilakukan',
    excerpt: 'Pemerintah mewajibkan implementasi Kurikulum Merdeka di semua sekolah pada 2027. Apa saja yang perlu dipersiapkan?',
    content: '<p>Kurikulum Merdeka akan menjadi kurikulum nasional yang wajib diimplementasikan di seluruh sekolah Indonesia mulai tahun 2027.</p>',
    channel: 'kebijakan',
    contentType: 'kurikulum-merdeka',
    tags: [MOCK_TAGS[0], MOCK_TAGS[11]],
    author: AUTHORS[6],
    publishedAt: '2026-06-17T11:00:00Z',
    readTime: 6,
    viewCount: 5432,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'keb-3',
    slug: 'regulasi-bar-tentang-bantuan-operasional-sekolah',
    title: 'Regulasi Terbaru Bantuan Operasional Sekolah (BOS) 2026',
    excerpt: 'Perubahan regulasi dana BOS 2026: alokasi, penggunaan, dan pelaporan. Simak panduan lengkapnya untuk sekolah.',
    content: '<p>Pemerintah telah menerbitkan regulasi baru mengenai pengelolaan dana Bantuan Operasional Sekolah (BOS) tahun 2026.</p>',
    channel: 'kebijakan',
    contentType: 'regulasi',
    tags: [MOCK_TAGS[11]],
    author: AUTHORS[5],
    publishedAt: '2026-06-16T07:00:00Z',
    readTime: 5,
    viewCount: 3456,
    isFeatured: false,
    isTrending: false,
  },

  // === TIPS MENGAJAR ===
  {
    id: 'tips-1',
    slug: 'strategi-classroom-management-siswa-aktif',
    title: '10 Strategi Classroom Management untuk Mengelola Siswa Aktif',
    excerpt: 'Tips praktis mengelola kelas dengan siswa yang hiperaktif. Strategi yang terbukti efektif dari guru berpengalaman.',
    content: '<p>Mengelola kelas dengan siswa yang aktif dan energik memang menantang. Berikut strategi yang telah terbukti efektif.</p>',
    channel: 'tips-mengajar',
    contentType: 'classroom-management',
    tags: [MOCK_TAGS[0]],
    author: AUTHORS[9],
    publishedAt: '2026-06-18T09:30:00Z',
    readTime: 7,
    viewCount: 4567,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'tips-2',
    slug: 'pembelajaran-diferensiasi-untuk-berbagai-gaya-belajar',
    title: 'Panduan Pembelajaran Diferensiasi untuk Berbagai Gaya Belajar Siswa',
    excerpt: 'Terapkan pembelajaran diferensiasi yang mengakomodasi gaya belajar visual, auditori, dan kinestetik di kelas Anda.',
    content: '<p>Pembelajaran diferensiasi adalah pendekatan yang menyesuaikan proses pembelajaran dengan kebutuhan belajar masing-masing siswa.</p>',
    channel: 'tips-mengajar',
    contentType: 'diferensiasi',
    tags: [MOCK_TAGS[0], MOCK_TAGS[8]],
    author: AUTHORS[7],
    publishedAt: '2026-06-17T10:00:00Z',
    readTime: 8,
    viewCount: 3456,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: 'tips-3',
    slug: 'teknik-konseling-singkat-untuk-guru-bk',
    title: 'Teknik Konseling Singkat (Solution-Focused Brief Counseling) untuk Guru BK',
    excerpt: 'Pelajari teknik konseling singkat yang efektif untuk membantu siswa mengatasi masalah akademik dan pribadi.',
    content: '<p>Solution-Focused Brief Counseling (SFBC) adalah pendekatan konseling yang berfokus pada solusi, bukan masalah.</p>',
    channel: 'tips-mengajar',
    contentType: 'konseling',
    tags: [MOCK_TAGS[0]],
    author: AUTHORS[9],
    publishedAt: '2026-06-16T08:00:00Z',
    readTime: 9,
    viewCount: 2345,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: 'tips-4',
    slug: 'program-literasi-sekolah-yang-menyenangkan',
    title: 'Program Literasi Sekolah yang Menyenangkan: Dari Membaca 15 Menit hingga Pameran Buku',
    excerpt: 'Ide kreatif program literasi sekolah yang mampu meningkatkan minat baca siswa secara signifikan.',
    content: '<p>Program literasi sekolah tidak harus membosankan. Berikut ide-ide kreatif yang telah berhasil diterapkan di berbagai sekolah.</p>',
    channel: 'tips-mengajar',
    contentType: 'literasi',
    tags: [MOCK_TAGS[9], MOCK_TAGS[0]],
    author: AUTHORS[3],
    publishedAt: '2026-06-15T07:00:00Z',
    readTime: 6,
    viewCount: 3120,
    isFeatured: false,
    isTrending: false,
  },
];

export function getContentByChannel(channel: string): ContentItem[] {
  return MOCK_CONTENT.filter((item) => item.channel === channel);
}

export function getFeaturedContent(): ContentItem[] {
  return MOCK_CONTENT.filter((item) => item.isFeatured);
}

export function getTrendingContent(): ContentItem[] {
  return MOCK_CONTENT.filter((item) => item.isTrending);
}

export function getContentBySlug(slug: string): ContentItem | undefined {
  return MOCK_CONTENT.find((item) => item.slug === slug);
}

export function getRelatedContent(content: ContentItem, limit = 4): ContentItem[] {
  const channelItems = MOCK_CONTENT.filter(
    (item) => item.channel === content.channel && item.id !== content.id
  );
  const tagItems = MOCK_CONTENT.filter(
    (item) =>
      item.id !== content.id &&
      item.channel !== content.channel &&
      item.tags.some((t) => content.tags.some((ct) => ct.id === t.id))
  );
  const combined = [...channelItems, ...tagItems];
  const unique = combined.filter(
    (item, index, self) => index === self.findIndex((t) => t.id === item.id)
  );
  return unique.slice(0, limit);
}

export function getContentByTag(tagSlug: string): ContentItem[] {
  return MOCK_CONTENT.filter((item) =>
    item.tags.some((t) => t.slug === tagSlug)
  );
}

export function searchContent(query: string): ContentItem[] {
  const q = query.toLowerCase();
  return MOCK_CONTENT.filter(
    (item) =>
      item.title.toLowerCase().includes(q) ||
      item.excerpt.toLowerCase().includes(q) ||
      item.tags.some((t) => t.name.toLowerCase().includes(q))
  );
}

export function getTagBySlug(slug: string) {
  return MOCK_TAGS.find((t) => t.slug === slug);
}